import {
  LayoutDashboard,
  GraduationCap,
  Users,
  School,
  BookOpen,
  Link2,
  CalendarCheck,
  ClipboardEdit,
  Award,
  Clock,
  Megaphone,
  PlaneTakeoff,
  BarChart3,
  Palette,
  Server,
  Wallet,
  Receipt,
  CreditCard,
  Bus,
  UserRound,
  Sparkles,
  Lock,
  HeartHandshake,
  Route,
  Map as MapIcon,
  Bell,
  Fingerprint,
  Banknote,
  Library,
  Boxes,
  Building2,
  Puzzle,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  students: GraduationCap,
  staff: Users,
  classes: School,
  subjects: BookOpen,
  allocation: Link2,
  attendance: CalendarCheck,
  marks: ClipboardEdit,
  results: Award,
  timetable: Clock,
  announce: Megaphone,
  leave: PlaneTakeoff,
  reports: BarChart3,
  branding: Palette,
  system: Server,
  wallet: Wallet,
  receipt: Receipt,
  card: CreditCard,
  bus: Bus,
  parent: HeartHandshake,
  users: Users,
  profile: UserRound,
  swan: Sparkles,
  lock: Lock,
  route: Route,
  map: MapIcon,
  bell: Bell,
  fingerprint: Fingerprint,
  banknote: Banknote,
  library: Library,
  boxes: Boxes,
  building: Building2,
  puzzle: Puzzle,
};
